<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>ml-media-archive</groupId>
  <artifactId>ml-media-archive</artifactId>
  <version>2.0.0</version>

  <properties>
    <java.version>22</java.version>
  </properties>


  <dependencies>
    <dependency>
      <groupId>com.codeborne</groupId>
      <artifactId>selenide</artifactId>
      <version>7.7.3</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <version>5.12.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>2.0.17</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <version>2.0.17</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>

      <plugin>
        <artifactId>maven-resources-plugin</artifactId>
        <version>3.2.0</version>
        <executions>
          <execution>
            <id>copy-static-files</id>
            <phase>process-resources</phase>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <configuration>
              <outputDirectory>${project.build.directory}</outputDirectory>
              <resources>
                <resource>
                  <directory>src/main/webapp</directory>
                  <includes>
                    <include>**/*.html</include>
                    <include>**/indexer.js</include>
                    <include>**/indexer.css</include>
                    <include>**/archive-search.html</include>
                    <include>**/archive-search.css</include>
                    <include>**/archive-search.js</include>
                    <include>**/ag-grid-community.min-33.2.2.js</include>
                    <include>**/z_cities1000_sorted_by_lon_lat.js</include>
                  </includes>
                </resource>
              </resources>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>3.5.0</version>
        <executions>
          <execution>
            <id>run-buildmerger</id>
            <phase>process-test-classes</phase>
            <goals>
              <goal>java</goal>
            </goals>
            <configuration>
              <mainClass>app.ml.media.archive.Builder</mainClass>
              <arguments>
                <argument>${project.build.directory}</argument>
              </arguments>
            </configuration>
          </execution>
        </executions>
      </plugin>
    
      <plugin>
        <artifactId>maven-antrun-plugin</artifactId>
        <version>3.0.0</version>
        <executions>
          <execution>
            <id>cleanup-target-folder</id>
            <phase>verify</phase>
            <goals>
              <goal>run</goal>
            </goals>
            <configuration>
              <target>
                <echo level="info">Delete unnecessary files [verify phase]</echo>

                <delete includeEmptyDirs="true">
                  <fileset dir="${project.build.directory}" defaultExcludes="no">
                    <include name="**/*" />
                    <exclude name="index.html" />
                    <exclude name="indexer.js" />
                    <exclude name="indexer.css" />
                    <exclude name="z_cities1000_sorted_by_lon_lat.js" />
                  </fileset>
                </delete>

              </target>
            </configuration>
          </execution>
        </executions>
      </plugin>

    </plugins>
  </build>
</project>
