#no automatic runs. Only manual run is possible.
trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  OUTPUT_FOLDER: 'target'  # Adjust to your actual output folder

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean verify'
    publishJUnitResults: false
    
- script: |
    echo "Listing files in output folder"
    ls -R $(OUTPUT_FOLDER)
  displayName: 'List build output files'

- script: |
    npm install -g @azure/static-web-apps-cli
  displayName: 'Install Azure Static Web Apps CLI'

- script: |
    swa deploy $(OUTPUT_FOLDER) --deployment-token $(SWA_DEPLOYMENT_TOKEN)
  env:
    SWA_DEPLOYMENT_TOKEN: $(SWA_DEPLOYMENT_TOKEN)
  displayName: 'Deploy to Azure Static Web App'
